@startuml

class Cocktail {
    - {field} Long id
    - {field} String name
    - {field} String description
    - {field} Recipe recipe
    - {field} String glass
    - {field} String created_user_id
    - {field} Timestamp createdDate
    - {field} Timestamp updatedDate
}

class Ingredient {
    - {field} Long id
    - {field} String name
    - {field} String description
    - {field} double abv
}

class Recipe {
    - {field} Long cocktail_id
    - {field} Long ingredient_id
    - {field} double abv
}

class User {
    - {field} Long id
    - {field} String name
    - {field} String login_id
    - {field} String pw
    - {field} Date birth_date
    - {field} String gender
    - {field} String phone_num
    - {field} Timestamp createdDate
    - {field} Timestamp updatedDate
}

Cocktail --> Recipe

@enduml